/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/courses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a course by ID
     * @description Returns the full details of a course including all instructor assignments.
     */
    get: operations["getCourse"];
    /**
     * Update a course
     * @description Updates an existing course's details and instructor assignments.
     */
    put: operations["updateCourse"];
    post?: never;
    /**
     * Delete a course
     * @description Deletes a course by ID. Only accessible to the owner of that course.
     */
    delete: operations["deleteCourse"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/labs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update course labs
     * @description Replaces the lab list for a course. Accepts own and public labs.
     */
    put: operations["updateCourseChallenges"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a lab by ID
     * @description Returns the full details of a lab. Visibility depends on status and user role.
     */
    get: operations["getChallenge"];
    /**
     * Update a lab
     * @description Updates an existing lab. Only the creator can update.
     */
    put: operations["updateChallenge"];
    post?: never;
    /**
     * Delete a lab
     * @description Deletes a lab and removes it from all courses. Only the creator can delete.
     */
    delete: operations["deleteChallenge"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAdminConfig"];
    put: operations["updateAdminConfig"];
    post: operations["uploadAndStoreAdminConfig"];
    delete: operations["deleteAdminConfig"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCourses"];
    put?: never;
    /**
     * Create a course
     * @description Creates a new course with its primary instructor and returns the persisted course.
     */
    post: operations["createCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/invite-code/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["regenerateInviteCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["enrollInCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/{id}/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["enrollInPublicCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["joinByInviteCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my labs
     * @description Returns a paginated list of labs created by the authenticated user.
     */
    get: operations["listChallenges"];
    put?: never;
    /**
     * Create a lab
     * @description Creates a new lab and returns the persisted lab.
     */
    post: operations["createChallenge"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lab-pods/{labId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPod"];
    put?: never;
    post: operations["startPod"];
    delete: operations["stopPod"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/instructors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCollaboratorUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/collaborators": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCollaboratorUsers_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/my-enrollments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listEnrollments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPublishedCourses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPublicCourse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs/{id}/visibility-impact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Preview visibility change impact
     * @description Returns how many course assignments would be removed if the lab's visibility were changed to the given status. Only the creator can call this.
     */
    get: operations["getVisibilityImpact"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/labs/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search available labs
     * @description Searches for labs by title. Returns the user's own labs and public ones.
     */
    get: operations["searchChallenges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateCourseInstructorRequestDto: {
      /** Format: uuid */
      instructorId: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
    };
    UpdateCourseRequestDto: {
      title: string;
      description?: string;
      shortDescription: string;
      imageUrl?: string;
      topic?: string;
      instructors: components["schemas"]["UpdateCourseInstructorRequestDto"][];
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CourseLabResponseDto: {
      /** Format: uuid */
      labId?: string;
      labTitle?: string;
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      orderIndex?: number;
      /** Format: date-time */
      dueAt?: string;
    };
    CourseDetailInstructorResponseDto: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
      instructor?: components["schemas"]["UserDto"];
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      acceptedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      accepted?: boolean;
    };
    CourseDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      participantCount?: number;
      imageUrl?: string;
      topic?: string;
      /** @enum {string} */
      difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
      inviteCode?: string;
      courseInstructors?: components["schemas"]["CourseDetailInstructorResponseDto"][];
      participants?: components["schemas"]["CourseParticipantResponseDto"][];
      courseLabs?: components["schemas"]["CourseLabResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      private?: boolean;
      enrolled?: boolean;
      published?: boolean;
      isEnrolled?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CourseParticipantResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      picture?: string;
    };
    UserDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      email?: string;
      username?: string;
      picture?: string;
      title?: string;
    };
    ErrorDto: {
      error?: string;
    };
    CourseLabItemDto: {
      /** Format: uuid */
      labId: string;
      /** Format: int32 */
      orderIndex: number;
      /** Format: date-time */
      dueAt?: string;
    };
    UpdateCourseLabsRequestDto: {
      labs: components["schemas"]["CourseLabItemDto"][];
    };
    UpdateChallengeRequestDto: {
      title: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
    };
    ChallengeCreatorResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
    };
    ChallengeDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      creator?: components["schemas"]["ChallengeCreatorResponseDto"];
      /** Format: int64 */
      courseCount?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    AdminConfigRequest: {
      cpuLimit?: string;
      memoryLimit?: string;
      kubeconfig?: string;
      /** Format: int32 */
      podTtlSeconds?: number;
    };
    AdminConfigResponse: {
      kubeconfigUploaded?: boolean;
      cpuLimit?: string;
      memoryLimit?: string;
      /** Format: int32 */
      podTtlSeconds?: number;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateCourseInstructorRequestDto: {
      /** Format: uuid */
      instructorId: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
    };
    CreateCourseRequestDto: {
      title: string;
      description?: string;
      shortDescription: string;
      imageUrl?: string;
      topic?: string;
      instructors: components["schemas"]["CreateCourseInstructorRequestDto"][];
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CreateCourseInstructorResponseDto: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
      instructor?: components["schemas"]["UserDto"];
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      acceptedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      accepted?: boolean;
    };
    CreateCourseResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      courseInstructors?: components["schemas"]["CreateCourseInstructorResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    PublicCourseDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      participantCount?: number;
      imageUrl?: string;
      topic?: string;
      /** @enum {string} */
      difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
      inviteCode?: string;
      courseInstructors?: components["schemas"]["CourseDetailInstructorResponseDto"][];
      participants?: components["schemas"]["CourseParticipantResponseDto"][];
      courseLabs?: components["schemas"]["ChallengeDetailResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      enrolled?: boolean;
      published?: boolean;
      isEnrolled?: boolean;
      isPublished?: boolean;
    };
    JoinByInviteCodeRequestDto: {
      code: string;
    };
    CreateChallengeRequestDto: {
      title: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
    };
    CreateChallengeResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      /** Format: uuid */
      creatorId?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    PodStatusResponse: {
      /** @enum {string} */
      status?: "NOT_FOUND" | "PROVISIONING" | "RUNNING" | "FAILED" | "TERMINATING";
      podName?: string;
      appUrl?: string;
      terminalUrl?: string;
      terminalPassword?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    ListInstructorUserResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      email?: string;
      username?: string;
      picture?: string;
      roles?: ("ROLE_ADMINISTRATOR" | "ROLE_INSTRUCTOR" | "ROLE_STUDENT")[];
    };
    PageListInstructorUserResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListInstructorUserResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      first?: boolean;
      last?: boolean;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    ListCourseResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      instructorCount?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      imageUrl?: string;
      topic?: string;
      /** @enum {string} */
      difficulty?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
      ownerName?: string;
      ownerPicture?: string;
      ownerTitle?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    PageListCourseResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListCourseResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      first?: boolean;
      last?: boolean;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    ListLabResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      creatorName?: string;
      /** Format: int64 */
      courseCount?: number;
      /** Format: date-time */
      updatedAt?: string;
    };
    PageListLabResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListLabResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      first?: boolean;
      last?: boolean;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    VisibilityImpactResponseDto: {
      /** Format: int32 */
      affectedCourseCount?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseRequestDto"];
      };
    };
    responses: {
      /** @description Course updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Invalid request data or referenced user not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  deleteCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateCourseChallenges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseLabsRequestDto"];
      };
    };
    responses: {
      /** @description Course labs updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course or lab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lab found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChallengeDetailResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Lab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateChallengeRequestDto"];
      };
    };
    responses: {
      /** @description Lab updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChallengeDetailResponseDto"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Lab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  deleteChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lab deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Lab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  updateAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminConfigRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  uploadAndStoreAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminConfigRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  deleteAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  listCourses: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
    };
  };
  createCourse: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseRequestDto"];
      };
    };
    responses: {
      /** @description Course created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CreateCourseResponseDto"];
        };
      };
      /** @description Invalid request data or referenced user not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  regenerateInviteCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
    };
  };
  enrollInCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
    };
  };
  enrollInPublicCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
    };
  };
  joinByInviteCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinByInviteCodeRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
    };
  };
  listChallenges: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Challenges retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListLabResponseDto"];
        };
      };
    };
  };
  createChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateChallengeRequestDto"];
      };
    };
    responses: {
      /** @description Lab created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CreateChallengeResponseDto"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PodStatusResponse"];
        };
      };
    };
  };
  startPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PodStatusResponse"];
        };
      };
    };
  };
  stopPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listCollaboratorUsers: {
    parameters: {
      query: {
        query?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListInstructorUserResponseDto"];
        };
      };
    };
  };
  listCollaboratorUsers_1: {
    parameters: {
      query: {
        query?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListInstructorUserResponseDto"];
        };
      };
    };
  };
  listEnrollments: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
    };
  };
  listPublishedCourses: {
    parameters: {
      query: {
        query?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
    };
  };
  getPublicCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
    };
  };
  getVisibilityImpact: {
    parameters: {
      query: {
        status: "DRAFT" | "PRIVATE" | "PUBLIC";
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Impact retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["VisibilityImpactResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Lab not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  searchChallenges: {
    parameters: {
      query: {
        q?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListLabResponseDto"];
        };
      };
    };
  };
}
