apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: istp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: istp
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret # created manually, see README
      containers:
        - name: frontend
          image: istp-frontend # replaced by overlay kustomization
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextauth-secret
                  key: NEXTAUTH_SECRET
            - name: KEYCLOAK_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: istp-config
                  key: keycloak-admin-url
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: istp-config
                  key: backend-url
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
