/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/courses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a course by ID
     * @description Returns the full details of a course including all instructor assignments.
     */
    get: operations["getCourse"];
    /**
     * Update a course
     * @description Updates an existing course's details and instructor assignments.
     */
    put: operations["updateCourse"];
    post?: never;
    /**
     * Delete a course
     * @description Deletes a course by ID. Only accessible to the owner of that course.
     */
    delete: operations["deleteCourse"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/challenges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update course challenges
     * @description Replaces the challenge list for a course. Accepts own and public challenges.
     */
    put: operations["updateCourseChallenges"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a challenge by ID
     * @description Returns the full details of a challenge. Visibility depends on status and user role.
     */
    get: operations["getChallenge"];
    /**
     * Update a challenge
     * @description Updates an existing challenge. Only the creator can update.
     */
    put: operations["updateChallenge"];
    post?: never;
    /**
     * Delete a challenge
     * @description Deletes a challenge and removes it from all courses. Only the creator can delete.
     */
    delete: operations["deleteChallenge"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/courses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["updateCourse_1"];
    post?: never;
    delete: operations["deleteCourse_1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAdminConfig"];
    put: operations["updateAdminConfig"];
    post: operations["uploadAndStoreAdminConfig"];
    delete: operations["deleteAdminConfig"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/challenges/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["updateChallenge_1"];
    post?: never;
    delete: operations["deleteChallenge_1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get courses for which the user is their instructor
     * @description Returns a paginated list of courses for which the user is their instructor (owner or collaborator).
     */
    get: operations["listCourses"];
    put?: never;
    /**
     * Create a course
     * @description Creates a new course with its primary instructor and returns the persisted course.
     */
    post: operations["createCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/invite-code/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Regenerate invite code
     * @description Regenerates the invite code of a private course. Only the course owner can perform this action.
     */
    post: operations["regenerateInviteCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["enrollInCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/{id}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Leave a course
     * @description Allows the authenticated student to remove themselves from a course they are enrolled in.
     */
    delete: operations["leaveCourse"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/{id}/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enroll in a course
     * @description Enroll in a course and returns the course in which the student enrolled themselves.
     */
    post: operations["enrollInPublicCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Join a private course by invite code
     * @description Enrolls the authenticated user into a private course using a 6-character invite code.
     */
    post: operations["joinByInviteCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my challenges
     * @description Returns a paginated list of challenges created by the authenticated user.
     */
    get: operations["listChallenges"];
    put?: never;
    /**
     * Create a challenge
     * @description Creates a new challenge and returns the persisted challenge.
     */
    post: operations["createChallenge"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenge-pods/{challengeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPod"];
    put?: never;
    post: operations["startPod"];
    delete: operations["stopPod"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{challengeId}/subtasks/{subTaskId}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a flag for a sub-task
     * @description Validates the submitted flag against the stored plaintext flag (case-sensitive). On a correct submission the sub-task is marked as solved for the authenticated user. Already-solved sub-tasks cannot be re-submitted.
     */
    post: operations["submitSubTaskFlag"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{challengeId}/subtasks/{subTaskId}/submit-choice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a multiple-choice answer for a sub-task
     * @description Records the student's selected option. Points awarded automatically when correct.
     */
    post: operations["submitSubTaskChoice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/k8s/pods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createPod"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listTopics"];
    put?: never;
    post: operations["addTopic"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/instructors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCollaboratorUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/collaborators": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCollaboratorUsers_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List course topics
     * @description Returns the list of allowed course topics for topic selection UIs.
     */
    get: operations["listCourseTopics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/my-enrollments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get enrolled courses of user (public and private)
     * @description Returns a paginated list of the enrolled courses of the user.
     */
    get: operations["listEnrollments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get published courses
     * @description Returns a paginated list of published courses.
     */
    get: operations["listPublishedCourses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/catalog/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a course by ID as a student
     * @description Returns a detailed response of a course for a student. User IDs are omitted due to security concerns.
     */
    get: operations["getPublicCourse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{id}/visibility-impact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Preview visibility change impact
     * @description Returns how many course assignments would be removed if the challenge's visibility were changed to the given status. Only the creator can call this.
     */
    get: operations["getVisibilityImpact"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/{id}/play": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a challenge in student play view
     * @description Returns a challenge formatted for students (no sub-task flags, with per-user solved progress). Caller must be enrolled in the given course, and the challenge must belong to it.
     */
    get: operations["getChallengeForPlay"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/challenges/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search available challenges
     * @description Searches for challenges by title. Returns the user's own challenges and public ones.
     */
    get: operations["searchChallenges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCourses_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/challenges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listChallenges_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/courses/{id}/participants/{participantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove a participant from a course
     * @description Removes a student (participant) from a course. Only accessible to the owner.
     */
    delete: operations["removeParticipant"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/k8s/pods/{instanceName}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deletePod"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/topics/{value}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteTopic"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateCourseInstructorRequestDto: {
      /** Format: uuid */
      instructorId: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
    };
    UpdateCourseRequestDto: {
      title: string;
      description?: string;
      shortDescription: string;
      imageUrl?: string;
      topic?: string;
      instructors: components["schemas"]["UpdateCourseInstructorRequestDto"][];
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CourseChallengeResponseDto: {
      /** Format: uuid */
      challengeId?: string;
      challengeTitle?: string;
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      orderIndex?: number;
      /** Format: date-time */
      dueAt?: string;
    };
    CourseDetailInstructorResponseDto: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
      instructor?: components["schemas"]["UserDto"];
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      acceptedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      accepted?: boolean;
    };
    CourseDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      participantCount?: number;
      imageUrl?: string;
      topic?: string;
      inviteCode?: string;
      courseInstructors?: components["schemas"]["CourseDetailInstructorResponseDto"][];
      participants?: components["schemas"]["CourseParticipantResponseDto"][];
      courseChallenges?: components["schemas"]["CourseChallengeResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      private?: boolean;
      enrolled?: boolean;
      published?: boolean;
      isEnrolled?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CourseParticipantResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      picture?: string;
    };
    UserDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      email?: string;
      username?: string;
      picture?: string;
      title?: string;
    };
    ErrorDto: {
      error?: string;
    };
    CourseChallengeItemDto: {
      /** Format: uuid */
      challengeId: string;
      /** Format: int32 */
      orderIndex: number;
      /** Format: date-time */
      dueAt?: string;
    };
    UpdateCourseChallengesRequestDto: {
      challenges: components["schemas"]["CourseChallengeItemDto"][];
    };
    SubTaskRequestDto: {
      /** Format: uuid */
      id?: string;
      title: string;
      description: string;
      flag?: string;
      /** Format: int32 */
      orderIndex?: number;
      /** @enum {string} */
      type?: "FLAG" | "MULTIPLE_CHOICE";
      /** Format: int32 */
      points?: number;
      hint?: string;
      options?: components["schemas"]["SubTaskOptionRequestDto"][];
    };
    UpdateChallengeRequestDto: {
      title: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      dockerImage: string;
      subTasks: components["schemas"]["SubTaskRequestDto"][];
    };
    ChallengeCreatorResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
    };
    ChallengeDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      dockerImage?: string;
      /** Format: int32 */
      maxScore?: number;
      dockerImage?: string;
      creator?: components["schemas"]["ChallengeCreatorResponseDto"];
      /** Format: int64 */
      courseCount?: number;
      subTasks?: components["schemas"]["SubTaskResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    SubTaskResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      flag?: string;
      /** Format: int32 */
      orderIndex?: number;
    };
    AdminUpdateCourseRequestDto: {
      title: string;
      description?: string;
      shortDescription?: string;
      topic?: string;
      imageUrl?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    AdminConfigRequest: {
      cpuLimit?: string;
      memoryLimit?: string;
      kubeconfig?: string;
      /** Format: int32 */
      podTtlSeconds?: number;
    };
    AdminConfigResponse: {
      kubeconfigUploaded?: boolean;
      cpuLimit?: string;
      memoryLimit?: string;
      /** Format: int32 */
      podTtlSeconds?: number;
      /** Format: date-time */
      updatedAt?: string;
    };
    AdminUpdateChallengeRequestDto: {
      title: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
    };
    CreateCourseInstructorRequestDto: {
      /** Format: uuid */
      instructorId: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
    };
    CreateCourseRequestDto: {
      title: string;
      description?: string;
      shortDescription: string;
      imageUrl?: string;
      topic?: string;
      instructors: components["schemas"]["CreateCourseInstructorRequestDto"][];
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    CreateCourseInstructorResponseDto: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      instructorRole?: "OWNER" | "COLLABORATOR";
      instructor?: components["schemas"]["UserDto"];
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      acceptedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      accepted?: boolean;
    };
    CreateCourseResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      courseInstructors?: components["schemas"]["CreateCourseInstructorResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    ChallengeStudentDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      dockerImage?: string;
      /** Format: int32 */
      maxScore?: number;
      creator?: components["schemas"]["ChallengeCreatorResponseDto"];
      subTasks?: components["schemas"]["SubTaskStudentDto"][];
      /** Format: int32 */
      solvedSubTaskCount?: number;
      /** Format: int32 */
      totalSubTaskCount?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      isSolved?: boolean;
    };
    PublicCourseDetailResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      participantCount?: number;
      imageUrl?: string;
      topic?: string;
      inviteCode?: string;
      courseInstructors?: components["schemas"]["CourseDetailInstructorResponseDto"][];
      participants?: components["schemas"]["CourseParticipantResponseDto"][];
      courseChallenges?: components["schemas"]["ChallengeStudentDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      enrolled?: boolean;
      published?: boolean;
      isEnrolled?: boolean;
      isPublished?: boolean;
    };
    SubTaskOptionStudentDto: {
      /** Format: uuid */
      id?: string;
      text?: string;
      /** Format: int32 */
      orderIndex?: number;
    };
    SubTaskStudentDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      /** Format: int32 */
      orderIndex?: number;
      /** @enum {string} */
      type?: "FLAG" | "MULTIPLE_CHOICE";
      /** Format: int32 */
      points?: number;
      hint?: string;
      options?: components["schemas"]["SubTaskOptionStudentDto"][];
      solvedFlag?: string;
      isSolved?: boolean;
      /** Format: uuid */
      selectedOptionId?: string;
    };
    ChoiceSubmissionRequestDto: {
      /** Format: uuid */
      selectedOptionId: string;
    };
    ChoiceSubmissionResponseDto: {
      isCorrect?: boolean;
      isChallengeSolved?: boolean;
      /** Format: int32 */
      solvedCount?: number;
      /** Format: int32 */
      totalCount?: number;
    };
    SubTaskOptionRequestDto: {
      /** Format: uuid */
      id?: string;
      text: string;
      isCorrect?: boolean;
      /** Format: int32 */
      orderIndex?: number;
    };
    JoinByInviteCodeRequestDto: {
      code: string;
    };
    CreateChallengeRequestDto: {
      title: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      dockerImage: string;
      subTasks: components["schemas"]["SubTaskRequestDto"][];
    };
    CreateChallengeResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      dockerImage?: string;
      /** Format: uuid */
      creatorId?: string;
      subTasks?: components["schemas"]["SubTaskResponseDto"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    SubTaskSubmissionRequestDto: {
      flag: string;
    };
    SubTaskSubmissionResponseDto: {
      /** Format: int32 */
      solvedSubTaskCount?: number;
      /** Format: int32 */
      totalSubTaskCount?: number;
      isCorrect?: boolean;
      isChallengeSolved?: boolean;
    };
    PodCreationRequest: {
      containerName?: string;
      image: string;
      /** Format: int32 */
      containerPort?: number;
    };
    PodCreationResponse: {
      status?: string;
      podName?: string;
      namespace?: string;
      message?: string;
      appUrl?: string;
      terminalUrl?: string;
      terminalPassword?: string;
    };
    PodStatusResponse: {
      /** @enum {string} */
      status?: "NOT_FOUND" | "PROVISIONING" | "RUNNING" | "FAILED" | "TERMINATING";
      podName?: string;
      appUrl?: string;
      terminalUrl?: string;
      terminalPassword?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    AdminTopicRequest: {
      value: string;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    ListInstructorUserResponseDto: {
      /** Format: uuid */
      id?: string;
      name?: string;
      email?: string;
      username?: string;
      picture?: string;
      roles?: ("ROLE_ADMINISTRATOR" | "ROLE_INSTRUCTOR" | "ROLE_STUDENT")[];
    };
    PageListInstructorUserResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListInstructorUserResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    ListCourseResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: int64 */
      instructorCount?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      imageUrl?: string;
      topic?: string;
      ownerName?: string;
      ownerPicture?: string;
      ownerTitle?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    PageListCourseResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListCourseResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    ListChallengeResponseDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      dockerImage?: string;
      creatorName?: string;
      /** Format: int64 */
      courseCount?: number;
      /** Format: date-time */
      updatedAt?: string;
    };
    PageListChallengeResponseDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListChallengeResponseDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    VisibilityImpactResponseDto: {
      /** Format: int32 */
      affectedCourseCount?: number;
    };
    AdminCourseListItemDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      shortDescription?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      topic?: string;
      imageUrl?: string;
      /** Format: uuid */
      ownerId?: string;
      ownerName?: string;
      ownerUsername?: string;
      private?: boolean;
      published?: boolean;
      isPublished?: boolean;
      isPrivate?: boolean;
    };
    PageAdminCourseListItemDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["AdminCourseListItemDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    AdminChallengeListItemDto: {
      /** Format: uuid */
      id?: string;
      title?: string;
      shortDescription?: string;
      description?: string;
      /** @enum {string} */
      status?: "DRAFT" | "PRIVATE" | "PUBLIC";
      /** @enum {string} */
      difficulty?: "BEGINNER" | "EASY" | "MEDIUM" | "HARD" | "EXPERT";
      /** Format: int32 */
      maxScore?: number;
      /** Format: int64 */
      courseCount?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      /** Format: uuid */
      creatorId?: string;
      creatorName?: string;
      creatorUsername?: string;
    };
    PageAdminChallengeListItemDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["AdminChallengeListItemDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseRequestDto"];
      };
    };
    responses: {
      /** @description Course updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Invalid request data or referenced user not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  deleteCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateCourseChallenges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCourseChallengesRequestDto"];
      };
    };
    responses: {
      /** @description Course challenges updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course or challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Challenge found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChallengeDetailResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateChallengeRequestDto"];
      };
    };
    responses: {
      /** @description Challenge updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChallengeDetailResponseDto"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  deleteChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Challenge deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  updateCourse_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminUpdateCourseRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteCourse_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  updateAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminConfigRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  uploadAndStoreAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminConfigRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["AdminConfigResponse"];
        };
      };
    };
  };
  deleteAdminConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  updateChallenge_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminUpdateChallengeRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteChallenge_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listCourses: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Courses found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  createCourse: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseRequestDto"];
      };
    };
    responses: {
      /** @description Course created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CreateCourseResponseDto"];
        };
      };
      /** @description Invalid request data or referenced user not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  regenerateInviteCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invite code regenerated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
      /** @description Access denied or invite code regeneration not allowed for public course */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  enrollInCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CourseDetailResponseDto"];
        };
      };
    };
  };
  enrollInPublicCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Enrolled in course */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
      /** @description Unexpected server error. Might occur, when user or course does not exist or the course is not public. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  joinByInviteCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinByInviteCodeRequestDto"];
      };
    };
    responses: {
      /** @description Joined course successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
      /** @description Invalid request payload or user not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Invalid or expired invite code */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  listChallenges: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Challenges retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListChallengeResponseDto"];
        };
      };
    };
  };
  createChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateChallengeRequestDto"];
      };
    };
    responses: {
      /** @description Challenge created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CreateChallengeResponseDto"];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  submitSubTaskFlag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challengeId: string;
        subTaskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubTaskSubmissionRequestDto"];
      };
    };
    responses: {
      /** @description Submission processed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["SubTaskSubmissionResponseDto"];
        };
      };
      /** @description Invalid flag format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description User not enrolled in a course containing this challenge */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge or sub-task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Sub-task already solved */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  submitSubTaskChoice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challengeId: string;
        subTaskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChoiceSubmissionRequestDto"];
      };
    };
    responses: {
      /** @description Submission processed */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "*/*": components["schemas"]["ChoiceSubmissionResponseDto"];
        };
      };
      /** @description User not enrolled */
      403: {
        headers: { [name: string]: unknown };
        content: { "*/*": components["schemas"]["ErrorDto"] };
      };
      /** @description Challenge, sub-task or option not found */
      404: {
        headers: { [name: string]: unknown };
        content: { "*/*": components["schemas"]["ErrorDto"] };
      };
    };
  };
  getPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challengeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PodStatusResponse"];
        };
      };
    };
  };
  startPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challengeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PodStatusResponse"];
        };
      };
    };
  };
  stopPod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challengeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createPod: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodCreationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PodCreationResponse"];
        };
      };
    };
  };
  listTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string[];
        };
      };
    };
  };
  addTopic: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminTopicRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  listCollaboratorUsers: {
    parameters: {
      query: {
        query?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListInstructorUserResponseDto"];
        };
      };
    };
  };
  listCollaboratorUsers_1: {
    parameters: {
      query: {
        query?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListInstructorUserResponseDto"];
        };
      };
    };
  };
  listCourseTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string[];
        };
      };
    };
  };
  listEnrollments: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Enrollments found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  listPublishedCourses: {
    parameters: {
      query: {
        query?: string;
        topic?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Courses found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListCourseResponseDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getPublicCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PublicCourseDetailResponseDto"];
        };
      };
      /** @description This can indicate one of two things. First this course is private and the user is neither an instructor of the course nor enrolled in the course. Second this course is a draft and the user is not an instructor of the course. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getVisibilityImpact: {
    parameters: {
      query: {
        status: "DRAFT" | "PRIVATE" | "PUBLIC";
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Impact retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["VisibilityImpactResponseDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  getChallengeForPlay: {
    parameters: {
      query: {
        courseId: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Challenge retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ChallengeStudentDto"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Challenge not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  searchChallenges: {
    parameters: {
      query: {
        q?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageListChallengeResponseDto"];
        };
      };
    };
  };
  listCourses_1: {
    parameters: {
      query: {
        q?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageAdminCourseListItemDto"];
        };
      };
    };
  };
  listChallenges_1: {
    parameters: {
      query: {
        q?: string;
        pageable: components["schemas"]["Pageable"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageAdminChallengeListItemDto"];
        };
      };
    };
  };
  removeParticipant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        participantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Participant removed successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
      /** @description Course or participant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  deletePod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instanceName: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        value: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  leaveCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully left the course */
      204: {
        headers: { [name: string]: unknown };
        content?: never;
      };
      /** @description Course not found or user not enrolled */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "*/*": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
}
