apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: istp
spec:
  storageClassName: cinder-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
