apiVersion: v1
kind: LimitRange
metadata:
  name: istp-default-container-limits
  labels:
    app.kubernetes.io/part-of: istp
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
