apiVersion: v1
kind: ResourceQuota
metadata:
  name: istp-namespace-quota
  labels:
    app.kubernetes.io/part-of: istp
spec:
  hard:
    pods: "120"
    services: "160"
    persistentvolumeclaims: "10"
    count/deployments.apps: "130"
    count/ingresses.networking.k8s.io: "130"
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
